# Generated by Django 4.2.11 on 2024-04-11 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("auto_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("class_begin", models.TimeField()),
                ("class_end", models.TimeField()),
                ("mon_class", models.BooleanField(default=False)),
                ("tues_class", models.BooleanField(default=False)),
                ("wed_class", models.BooleanField(default=False)),
                ("thurs_class", models.BooleanField(default=False)),
                ("fri_class", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("auto_id", models.AutoField(primary_key=True, serialize=False)),
                ("instructor", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRCodeUpload",
            fields=[
                ("auto_id", models.AutoField(primary_key=True, serialize=False)),
                ("qr_image", models.ImageField(upload_to="data")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRcode",
            fields=[
                ("auto_id", models.AutoField(primary_key=True, serialize=False)),
                ("qrcode", models.CharField(max_length=32)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "courses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.person"
            ),
        ),
    ]
