# Generated by Django 5.0.3 on 2024-04-17 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="UniversityPerson",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="auto_id",
            new_name="auto_increment_id",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="class_begin",
            new_name="class_start",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="fri_class",
            new_name="f_class",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="faculty",
            new_name="instructor",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="mon_class",
            new_name="m_class",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="thurs_class",
            new_name="th_class",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="tues_class",
            new_name="tu_class",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="wed_class",
            new_name="w_class",
        ),
        migrations.RenameField(
            model_name="qrcode",
            old_name="auto_id",
            new_name="auto_increment_id",
        ),
        migrations.RenameField(
            model_name="qrcode",
            old_name="qrcode",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="qrcodeupload",
            old_name="auto_id",
            new_name="auto_increment_id",
        ),
        migrations.RenameField(
            model_name="qrcodeupload",
            old_name="qr_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="universityperson",
            old_name="auto_id",
            new_name="auto_increment_id",
        ),
        migrations.RenameField(
            model_name="universityperson",
            old_name="instructor",
            new_name="is_instructor",
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name="Lecture",
        ),
    ]
