# Generated by Django 5.0.3 on 2024-05-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_course_sat_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="red_flags")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=256)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.universityperson",
                    ),
                ),
            ],
        ),
    ]
